"""create chat module

Revision ID: 077791dd362c
Revises: 10bc30456861
Create Date: 2026-07-05 10:22:58.904213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '077791dd362c'
down_revision: Union[str, Sequence[str], None] = '10bc30456861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_rooms', sa.Column('is_ai', sa.Boolean(), nullable=False))
    op.add_column('chat_rooms', sa.Column('last_message', sa.String(length=500), nullable=True))
    op.alter_column('chat_rooms', 'pakar_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('chat_rooms', 'is_closed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_rooms', 'is_closed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('chat_rooms', 'pakar_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('chat_rooms', 'last_message')
    op.drop_column('chat_rooms', 'is_ai')
    # ### end Alembic commands ###
