"""update peternakan fields

Revision ID: 10bc30456861
Revises: 75129ad9365e
Create Date: 2026-07-05 09:49:39.438080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10bc30456861'
down_revision: Union[str, Sequence[str], None] = '75129ad9365e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peternakan', sa.Column('jenis_ternak', sa.String(length=100), nullable=False))
    op.add_column('peternakan', sa.Column('jumlah_ternak', sa.Integer(), nullable=False))
    op.add_column('peternakan', sa.Column('jenis_pakan', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('peternakan', 'jenis_pakan')
    op.drop_column('peternakan', 'jumlah_ternak')
    op.drop_column('peternakan', 'jenis_ternak')
    # ### end Alembic commands ###
